### ISSUE TITLE
Version 2.0: Exception - Required value 'modeRules' missing at $

### ISSUE THREAD

**Issue by luzianscherrer** [admin-ch/CovidCertificate-SDK-Android#97]
I'm trying out the new versions sdk-android:2.0 / sdk-core:3.0. I get the following exception on refreshTrustList:

```
2021-12-10 10:20:31.993 29080-30773/ch.ooqi.ooqicheckin E/CertificateVerificationController: Manually refreshing trust list failed
    com.squareup.moshi.JsonDataException: Required value 'modeRules' missing at $
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:649)
        at ch.admin.bag.covidcertificate.sdk.core.models.trustlist.RuleSetJsonAdapter.fromJson(RuleSetJsonAdapter.kt:83)
        at ch.admin.bag.covidcertificate.sdk.core.models.trustlist.RuleSetJsonAdapter.fromJson(RuleSetJsonAdapter.kt:25)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:46)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

Does it need some additional initialization or what am I missing?

**Comment by goebelUB** [comment]
The production backend is not yet deployed with the latest API changes. Pleae check again on Monday.
Meanwhile, you can use the ABN and DEV environments for testing.
These test certs should be valid on ABN: https://github.com/eu-digital-green-certificates/dgc-testdata/tree/main/CH

**Comment by luzianscherrer** [comment]
Just tried it on ABN but I get the following:

`INVALID(signatureState=INVALID(signatureErrorCode=S|CSI), revocationState=ch.admin.bag.covidcertificate.sdk.core.models.state.CheckRevocationState$SUCCESS@1d7800d, nationalRulesState=SUCCESS(validityRange=null, isOnlyValidInCH=false), validityRange=ValidityRange(validFrom=2021-08-01T00:00, validUntil=2022-07-31T00:00))
`

Also, is it correct to use the string THREE_G or TWO_G as verificationModeIdentifier argument to the very function? I just want to make sure because it's not really documented.

**Comment by luzianscherrer** [comment]
I'm sorry I think I have messed up the environment initialization. It is generally working now.

The test certificate on the page that you've mentioned did expire on 2021-08-21T12:00. I have create a new one: [covid-certificate-1639134734782.pdf](https://github.com/admin-ch/CovidCertificate-SDK-Android/files/7692294/covid-certificate-1639134734782.pdf)

But apparently no matter what verificationModeIdentifier string I'm using as argument to verify, it always gets accepted. What is the correct way to only allow 2G?

**Comment by goebelUB** [comment]
I added some documentation in #98 to the [README](https://github.com/admin-ch/CovidCertificate-SDK-Android#verification-1) on how to use the verification modes. Let me know if that helps or if you need more information.

**Comment by goebelUB** [comment]
The trustlist contains **both** the verification rules and the available verification modes.

Thus as long as you do not refresh the trustlist in between, you should not need to getActiveModes every single time.
For example if you refresh the trustlist once at the app start then you can just get the active modes once after that.
But good point, I'll have to double check that we actually do this in our apps...

**Comment by luzianscherrer** [comment]
I'm still a bit confused about how it all plays together. 

Are the following two assumptions correct?

1. `refreshTrustList` is an online operation fetching the verification rules and the verification modes
2. `getActiveModes() / collect` is an offline operation querying the locally stored data downloaded in step 1

As far as I understand the `refreshTrustList` is triggered periodically (every hour?). Wouldn't that then potentially make the result that I got earlier from `getActiveModes() / collect` obsolete?

**Comment by goebelUB** [comment]
2. is correct, 1. is also correct with the addition that it may use a local cache if the device is offline.

One thing to note (that I also had to read up) is that `getActiveModes` returns a [StateFlow](https://developer.android.com/kotlin/flow/stateflow-and-sharedflow). **Since it is a Flow, the lambda you pass to `collect` will be called every time the flow emits a new value.** This is all pretty similar to the good-old `LiveData`.

Now, looking at [`refreshTrustlist`](https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/repository/TrustListRepository.kt#L54) we see that it updates the SDK-internal `activeModes.value`, which SDK users then "listen to" using [`getActiveModes`'s StateFlow](https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/CovidCertificateSdk.kt#L206).

Thus you don't need to explicitly call `getActiveModes` all the time. Instead, your "`collect`-lambda" will automagically be called again whenever the trustlist was refreshed.

**Comment by luzianscherrer** [comment]
Very enlightening, thank you for explaining it.

I have two additional questions:

a) Since I'm wrapping it all up in Java, I'm not 100% sure if those mechanisms will work for me as intended. Is there a way for me to test the update of the activeModes?

b) Since in version 2.0 I now _have_ to pass a verificationModeIdentifier to the verifier, is it true that light certificates are not supported any more? Or what would I pass as verificationModeIdentifier if I just wanted to check for VerificationState.SUCCESS (as I'm currently doing with version 1.x) and not care about the ModeValidityState?

**Comment by luzianscherrer** [comment]
I have figured question b) out by now. You always pass a `verificationModeIdentifier` and you always check with `getModeValidity()`. If the passed mode does not support light certificates - as is currently only the case with `TWO_G` - you get `ModeValidityState.IS_LIGHT`. Please correct me if I'm wrong.

My only concern now is question a), ie. that I'm not able to test my code for the case of an update to the `activeModes` list. I  thus propose the following: If you could on the ABN environment have one of the modes duplicated (for example `THREE_G_COPY`) and then have it periodically added and removed every x hours, that would allow us who are implementing the SDK to test the behaviour. The other option would of course be to run a test in coordination with you, but I think the first suggestion might be helpful for others as well.
